catalog/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('', views.index, name="index"),
    path('books/', views.BookListView.as_view(), name="books"),
    path('book/<int:pk>', views.BookDetailView.as_view(), name='book-detail'),
    path('authors/', views.AuthorListView.as_view(), name='authors'),
    path('author/<int:pk>', views.AuthorDetailView.as_view(), name='author-detail'),
    path('mybooks/', views.LoanedBooksByUserListView.as_view(), name='my-borrowed'),
    path('loanedbooks/', views.AllLoanedBooksView.as_view(), name='all-loaned'),
]

urlpatterns += [
    path('author/create', views.AuthorCreate.as_view(), name='author-create'),
    path('author/<int:pk>/update',
         views.AuthorUpdate.as_view(), name='author-update'),
    path('author/<int:pk>/delete/',
         views.AuthorDelete.as_view(), name='author-delete'),
]

urlpatterns += [
    path('book/create', views.BookCreate.as_view(), name='book-create'),
    path('book/<int:pk>/update', views.BookUpdate.as_view(), name='book-update'),
    path('book/<int:pk>/delete/', views.BookDelete.as_view(), name='book-delete'),
]

urlpatterns += [
    path('bookreview/', (views.ReviewFormView.as_view()),
         name="book-review-form")
]
urlpatterns += [
    path('register/', views.register, name="register")
]

emilyslibrary/urls.py
from django.conf.urls.static import static
from django.conf import settings
from django.views.generic import RedirectView
from django.urls import include
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

urlpatterns += [
    path('catalog/', include('catalog.urls')),
]

urlpatterns += [
    path('', RedirectView.as_view(url='catalog/', permanent=True)),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns += [
    path('accounts/', include('django.contrib.auth.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

catalog/models.py
from django.db import models
from django.urls import reverse
import uuid
from django.contrib.auth.models import User
from django.utils import timezone
from datetime import datetime
from datetime import date


# Genre model


class Genre(models.Model):
    """ Model representing a book genre."""
    name = models.CharField(max_length=200, help_text="Enter a book genre")

    class Meta:
        permissions = (("can_add", "Can add genres"),)

    def __str__(self):
        """String for representing the Model object"""
        return self.name


# Review model


# Book Model


class Book(models.Model):
    """Model representing a book (but not a specific copy of a book)"""
    title = models.CharField(max_length=200)
    isbn = models.CharField('ISBN', max_length=13, unique=True,
                            help_text='13 character unique identifier for a book')

    description = models.TextField(
        max_length=1000, help_text='Enter a brief summary', blank=True)

    cover_img = models.ImageField(
        upload_to='book_covers/', null=True, blank=True)
    publication_date = models.DateField(blank=True, default=date.today)
    # foreign key used because a book can only have one author, but authors can have written multiple books
    author = models.ForeignKey('Author', on_delete=models.SET_NULL, null=True)

    # many to many field used because books can have many genres and genres can contain many books
    genre = models.ManyToManyField(
        Genre, help_text='Select a genre for this book')

    class Meta:
        permissions = (("can_edit", "Edit existing books"), ("can_add", "Can add new books"),
                       ('can_delete', "Can delete books"))

    def __str__(self):
        """ String representation of the Model object"""
        return self.title

    def get_absolute_url(self):
        """ Returns the url to access a detail record for this book"""
        return reverse('book-detail', args=[str(self.id)])

    def display_genre(self):
        """Create a string for the genre, required to display genre in admin view"""
        return ', '.join(genre.name for genre in self.genre.all()[:3])

    display_genre.short_description = 'Genre'

    def at_least_one_bookinst_is_avail(self):
        book_insts = BookInstance.objects.filter(book=self)
        for inst in book_insts:
            if inst.status == 'a':
                return True
        return False

    def num_copies_avail(self):
        book_insts = BookInstance.objects.filter(book=self)
        num_avail = 0
        for book in book_insts:
            if book.status == 'a':
                num_avail += 1
        return num_avail

    def total_copies(self):
        return BookInstance.objects.filter(book=self).count()

    def average_review(self):
        reviews = Review.objects.filter(book=self)
        counter = 0
        summer = 0
        for review in reviews:
            summer += review.stars
            counter += 1
        if counter == 0:
            return -1
        return summer/counter

    # def display_num_of_reviews(self):
    #     """Create a string showing how many reviews a book has"""
    #     count = self.review.all().count()
    #     return count

    #display_num_of_reviews.short_description = "Number of Reviews"


class Review(models.Model):
    """ Model representing a book review"""
    writer = models.CharField(
        max_length=200, help_text='Enter author of review')
    body = models.TextField(max_length=2000, help_text='Review contents')
    stars = models.IntegerField(
        help_text='Enter how many stars the reviewer gave')

    date_written = models.DateField(
        default=date.today, blank=True)
    book = models.ForeignKey(
        Book, on_delete=models.CASCADE, null=True, related_name="reviews")

    class Meta:
        ordering = ['date_written']

    def __str__(self):
        """String representing the model object"""
        return self.body

    # def get_date_written(self):
    #     return date_written.date()


class BookInstance(models.Model):
    """ Model representing a specific copy of a book (that can be borrowed from the library)"""
    id = models.UUIDField(primary_key=True, default=uuid.uuid4,
                          help_text="Unique ID for this book")
    book = models.ForeignKey('Book', on_delete=models.RESTRICT, null=True)
    imprint = models.CharField(max_length=200)
    borrower = models.ForeignKey(
        User, on_delete=models.SET_NULL, null=True, blank=True)
    LOAN_STATUS = (
        ('a', 'Available'),
        ('r', 'Reserved'),
        ('o', 'Checked Out'),
        ('u', 'Unavailable')
    )

    status = models.CharField(
        max_length=1,
        choices=LOAN_STATUS,
        blank=True,
        default='u',
        help_text='Book availability',
    )

    class Meta:
        permissions = (("can_marked_returned", "Set book as returned"),
                       ("can_add_edit", "Can add/edit book instances"),)

    def __str__(self):
        """String representing the model object"""
        return f'{self.id} ({self.book.title})'

    def get_status(self):
        return self.status


class Author(models.Model):
    """Model representing an Author"""
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=200)
    date_of_birth = models.DateField(null=True, blank=True)
    date_of_death = models.DateField('Died', null=True, blank=True)

    class Meta:
        ordering = ['last_name', 'first_name']
        permissions = (("can_add", "Can add authors"),
                       ("can_edit", "Can edit authors"),
                       ("can_delete", "Can delete authors"))

    def get_absolute_url(self):
        """Returns the url to access a particulat author instance"""
        return reverse('author-detail', args=[str(self.id)])

    def __str__(self):
        """String representation for the Model object"""
        return f'{self.last_name}, {self.first_name}'

catalog/forms.py
from django import forms
from django.core.exceptions import ValidationError
from django.utils.translation import ugettext_lazy as _
from .models import Review
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class ReviewForm(forms.ModelForm):
    class Meta:
        model = Review
        fields = '__all__'


class RegisterForm(UserCreationForm):
    email = forms.EmailField()
    first_name = forms.CharField(max_length=100)
    last_name = forms.CharField(max_length=100)

    class Meta:
        model = User
        fields = ['username', 'first_name', 'last_name',
                  'email', 'password1', 'password2']

catalog/views.py
from django.shortcuts import render, redirect
from .models import Book, Author, BookInstance, Genre, Review
from django.views import generic, View
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.mixins import PermissionRequiredMixin
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy
from django import forms
from django.urls import reverse
from django.http import HttpResponseForbidden, HttpResponseRedirect
from django.views.generic import FormView
from django.views.generic.detail import SingleObjectMixin
from django_filters.views import FilterView


from catalog.models import Author, Review
from catalog.models import Book
# from catalog.filters import BookFilter
from .forms import ReviewForm, RegisterForm


def index(request):
    """View function for the home page of site"""

    num_books = Book.objects.all().count()
    num_instances = BookInstance.objects.all().count()

    # Available books
    num_instances_avail = BookInstance.objects.filter(
        status__exact='a').count()

    num_authors = Author.objects.count()

    # number of visits to this view, as counted in the session variable
    num_visits = request.session.get('num_visits', 0)
    request.session['num_visits'] = num_visits + 1

    context = {
        'num_books': num_books,
        'num_instances': num_instances,
        'num_instances_avail': num_instances_avail,
        'num_authors': num_authors,
        'num_visits': num_visits,
    }

    return render(request, 'index.html', context=context)


class BookListView(generic.ListView):
    model = Book
    paginate_by = 12

    def get_queryset(self):
        filter_val = self.request.GET.get('filter')
        queryset = super().get_queryset()
        if filter_val:
            return queryset.filter(title__icontains=filter_val)
        else:
            return queryset


class BookDetailView(generic.DetailView):
    model = Book
    template_name = 'catalog/book_detail.html'
    form_class = ReviewForm

    def get_context_data(self, **kwargs):
        context = super(BookDetailView, self).get_context_data(**kwargs)
        context['form'] = ReviewForm
        return context


class ReviewFormView(FormView):
    form_class = ReviewForm
    success_url = reverse_lazy('books')
    model = Review
    book_pk = None

    def get_book(self):
        return Review.objects.first().book

    def form_valid(self, form):
        temp = form.cleaned_data.get("book")
        self.book_pk = temp.pk
        item = form.save()
        return super(ReviewFormView, self).form_valid(form)

    def get_success_url(self):
        return reverse('book-detail', args=[str(self.book_pk)])


class AuthorListView(generic.ListView):
    model = Author
    paginate_by = 10


class AuthorDetailView(generic.DetailView):
    model = Author


class ReviewListView(generic.ListView):
    model = Review


class LoanedBooksByUserListView(LoginRequiredMixin, generic.ListView):
    """ Generic class-based view listing books on loan to current user"""
    """Must be logged in to see it (loginrequiredmixin checks this)"""
    model = BookInstance
    template_name = 'catalog/bookinstance_list_borrowed_user.html'
    paginate_by = 10

    def get_queryset(self):
        return BookInstance.objects.filter(borrower=self.request.user).filter(status__exact='o')


class AllLoanedBooksView(PermissionRequiredMixin, generic.ListView):
    """Generic class-based view listing all books on loan and the borrowers"""
    permission_required = 'catalog.can_add_edit'
    model = BookInstance
    template_name = 'catalog/all_loaned_books.html'
    paginate_by = 10

    def get_queryset(self):
        return BookInstance.objects.filter(borrower__isnull=False)


class AuthorCreate(CreateView):
    model = Author
    fields = ['first_name', 'last_name', 'date_of_birth', 'date_of_death']


class AuthorUpdate(UpdateView):
    model = Author
    fields = '__all__'  # not necessarily best practice


class AuthorDelete(DeleteView):
    model = Author
    success_url = reverse_lazy('authors')


class BookCreate(CreateView):
    model = Book
    fields = ['title', 'isbn', 'description', 'cover_img', 'author', 'genre']


class BookUpdate(UpdateView):
    model = Book
    fields = ['title', 'isbn', 'description', 'author', 'genre']


class BookDelete(DeleteView):
    model = Book
    success_url = reverse_lazy('books')


def register(response):
    if response.method == 'POST':
        form = RegisterForm(response.POST)
        if form.is_valid():
            form.save()
        return redirect("/accounts/login/")
    else:
        form = RegisterForm()

    return render(response, 'catalog/register.html', {"form": form})

catalog/templates/catalog/all_loaned_books.html
{% extends "base_generic.html" %}

{% block content %}
<h1>All Borrowed Books</h1>
{% if bookinstance_list %}
<ul>
  {% for bookins in bookinstance_list %}
  <li><a href="{% url 'book-detail' bookins.book.pk %}">{{ bookins.book.title }}</a> - {{ bookins.borrower }}</li>
  {% endfor %}

</ul>
{% else %}
<p>No books are currently checked out.</p>
{% endif %}
{% endblock %}

catalog/templates/catalog/author_confirm_delete.html
{% extends "base_generic.html" %}
{% block content %}

<h1> Delete Author</h1>

<p>Are you sure you want to delete the author: {{ author }}?</p>

<form action="" method="post">
  {% csrf_token %}
  <input type="submit" value="Yes, I'm sure.">
</form>
{% endblock %}

catalog/templates/catalog/author_detail.html
{% extends "base_generic.html" %}

{% block content %}
<h1>{{ author.first_name }} {{ author.last_name }}</h1>

<p><strong>Date of Birth:</strong> {{ author.date_of_birth }}</p>
<p><strong>Date of Death:</strong> {{ author.date_of_death }}</p>


{% endblock %}

catalog/templates/catalog/author_form.html
{% extends "base_generic.html" %}

{% block content %}
<form action="" method="post">
  {% csrf_token %}
  <table>
    {{ form.as_table }}
  </table>
  <input type="submit" value="Submit">
</form>
{% endblock %}

catalog/templates/catalog/author_list.html
{% extends "base_generic.html" %}

{% block content %}

<h1>Author List</h1>
{% if author_list %}
<ul>
  {% for author in author_list %}
  <li>
    <a href="{{ author.get_absolute_url }}">{{ author.first_name }} {{author.last_name }}</a>

  </li>
  {% endfor %}

</ul>
{% else %}
<p>there are no authors.</p>
{% endif %}
{% endblock %}

catalog/templates/catalog/book_confirm_delete.html
{% extends "base_generic.html" %}

{% block content %}

<h1>Delete Book</h1>

<p>Are you sure you want to delete {{ book }}?</p>

<form action="" method="post">
  {% csrf_token %}
  <input type="submit" value="Yes, I'm sure.">
</form>
{% endblock %}

catalog/templates/catalog/book_detail.html
{% extends "base_generic.html" %}

{% block content %}
<div class="book-detail">

  {% if book.cover_img %}
  <img class="book-cover-detail" src="{{ book.cover_img.url }}">
  {% endif %}
  <div class="details">
    <h1>{{ book.title }}</h1>
    <p><strong>By:</strong> <a href="{{ book.author.get_absolute_url }}">{{ book.author.first_name }}
        {{ book.author.last_name }}</a></p>
    <p class="isbn">{{ book.isbn }}</p>
    <p class="avg_review">
      {% if book.average_review == -1 %}
      <strong>No reviews yet</strong>
      {% else %}
      <strong>{{ book.average_review }}</strong>

      {% load static %}
      <img src="{% static 'img/star.png' %}">
      {% endif %}
    </p>
    {% for genre in book.genre.all %}
    <span class="genre-bubble-list">{{ genre }} </span>
    {% endfor %}
    <br />
    <br />
    <div class="copies-avail">
      {% load static %}
      <img src="{% static 'img/book.png' %}">
      {{ book.num_copies_avail }} of {{ book.total_copies }} Copies Available
    </div>
    <hr>
    <p><strong>Description:</strong>{{ book.description }}</p>
    <p><strong>Reviews:</strong>{{ book.reviews.all|join:"; " }}</p>
  </div>

  <form method="post" action="{% url 'book-review-form' %}">
    {% csrf_token %}
    {{ form }}
    <input type="submit" value="Submit">
  </form>
</div>

{% endblock %}

catalog/templates/catalog/book_form.html
{% extends "base_generic.html" %}
{% block content %}
<form action="" method="post" enctype="multipart/form-data">
  {% csrf_token %}
  <table>
    {{ form.as_table }}
  </table>
  <input type="submit" value="Submit">
</form>
{% endblock %}

catalog/templates/catalog/book_list.html
{% extends "base_generic.html" %}

{% block content %}

<h1 class="book-list-header">All Books</h1>
<div class="list-sidebar">
  hello
  <form method="get" action="{% url 'books' %}">
    <p>Filter: <input type="text" name="filter" value="{{ request.GET.filter }}" /></p>
    <p>order_by: <input type="text" name="orderby" /></p>
    <p><input type="submit" value="submit" /></p>
  </form>
</div>
<div class="book-list">

  {% if book_list %}
  <ul class="flex-container">
    {% for book in book_list %}
    <li class="flex-item">
      <div class="availability-text">
        {% if book.at_least_one_bookinst_is_avail %}
        Available
        {% else %}
        Unavailable
        {% endif %}
      </div>
      {% if book.cover_img %}
      <div class="cover-image-book-list">
        <a href=" {{ book.get_absolute_url }}"><img src="{{ book.cover_img.url }}"></a>
      </div>
      {% endif %}
      <div class="stars-list">
        {% if book.average_review == -1 %}
        N/A
        {% else %}
        {{ book.average_review }}
        {% endif %}
        {% load static %}
        <img src="{% static 'img/star.png' %}">
      </div>
      <div class="book-title-list">
        <a href=" {{ book.get_absolute_url }}">{{ book.title }}</a>
      </div>

      <div class="author-book-list">
        by: <a href=" {{ book.author.get_absolute_url }}">{{ book.author }}</a>
      </div>
      <div class="genre-book-list">
        {% for genre in book.genre.all %}
        <span class="genre-bubble">{{ genre}} </span>
        {% endfor %}
      </div>
    </li>
    {% endfor %}

  </ul>
  {% else %}
  <p> there are no books in the library.</p>
  {% endif %}
</div>

{% endblock %}

catalog/templates/catalog/bookinstance_list_borrowed_user.html
{% extends "base_generic.html" %}

{% block content %}
<h1>Borrowed Books</h1>
{% if bookinstance_list %}
<ul>
  {% for bookinst in bookinstance_list %}
  <li>
    <a href="{% url 'book-detail' bookinst.book.pk %}">{{ bookinst.book.title }}</a>
  </li>
  {% endfor %}

</ul>
{% else %}
<p>There are no books borrowed.</p>
{% endif %}
{% endblock %}

catalog/templates/catalog/register.html
{% extends "base_generic.html" %}


{% block content %}
{% if user.is_authenticated %}
<h1> Whoops! Look's like you're already logged in!</h1>
<a href="{% url 'index' %}">Back Home</a>
{% else %}
<h1>Create an account</h1>

<form method="POST">
  {% csrf_token %}
  {{ form }}
  <input type="submit" name="Submit">
</form>
{% endif %}
{% endblock %}